using System;
using System.Collections.Generic;
using System.IO;
using Assimp;
using OpenTK;

//mostly generated by Chatty gpt

namespace GeometryExport
{
    public sealed class GeometryObject
    {
        public string Name;

        // Required
        public List<Vector3D> Positions { get; } = new();
        public List<int> Indices { get; } = new(); // triangles: count % 3 == 0

        // Optional but recommended
        public List<Vector3D>? Normals { get; set; } = new();       // same count as Positions if present
        public List<Vector3D>? UVs0 { get; set; } = new();             // use X,Y as UV; Z ignored
        public List<Vector3D>? UVs1 { get; set; } = new();                                                                // (Assimp uses Vector3D for UVs)

        public string DiffuseTexturePath;
        public string LightMapPath;

        public GeometryObject(List<List<float>> vertexdata,
            List<int> indexdata,
            string name,
            string DiffuseTexturePath, string LightMapPath)
        {
            Name = name;
            Indices = indexdata;

            for(int i=0; i < vertexdata[0].Count; i += 3)
            {
                Positions.Add(new Vector3D(vertexdata[0][i], vertexdata[0][i + 1], vertexdata[0][i + 2]));
            }

            for (int i = 0; i < vertexdata[1].Count; i += 3)
            {
                Normals.Add(new Vector3D(vertexdata[1][i], vertexdata[1][i + 1], vertexdata[1][i + 2]));
            }

            for (int i = 0; i < vertexdata[3].Count; i += 2)
            {
                UVs0.Add(new Vector3D(vertexdata[3][i], -vertexdata[3][i + 1], 0));
            }

            for (int i = 0; i < vertexdata[4].Count; i += 2)
            {
                UVs1.Add(new Vector3D(vertexdata[4][i], -vertexdata[4][i + 1], 0));
            }

            this.DiffuseTexturePath = DiffuseTexturePath;
            this.LightMapPath = LightMapPath;
        }
    }

    public static class aGeometryExporter
    {
        

        public static void Export(
            IReadOnlyList<GeometryObject> objects,
            string outputPath,
            string? formatId = null)
        {
            if (objects == null) throw new ArgumentNullException(nameof(objects));
            if (objects.Count == 0) throw new ArgumentException("No objects to export.", nameof(objects));
            if (string.IsNullOrWhiteSpace(outputPath)) throw new ArgumentNullException(nameof(outputPath));

            var scene = BuildScene(objects);

            using var ctx = new AssimpContext();

            // Infer format from extension if not provided
            formatId ??= InferFormatIdFromExtension(outputPath);

            // Export
            ctx.ExportFile(scene, outputPath, formatId);
        }

        private static TextureSlot Slot(string path, TextureType textype, int uvChannel = 0)
        {
            return new TextureSlot(
                    filePath: path,
                    typeSemantic: textype,
                    texIndex: 0,
                    mapping: TextureMapping.FromUV,
                    uvIndex: uvChannel,
                    blendFactor: 1.0f,
                    texOp: TextureOperation.Add,
                    wrapModeU: TextureWrapMode.Wrap,
                    wrapModeV: TextureWrapMode.Wrap,
                    flags: 0
                );
        }

        private static void ApplyTextures(Material mat, GeometryObject obj)
        {
            // Prefer relative paths for portability (e.g. "Textures/Wood_BaseColor.png")
            if (!string.IsNullOrWhiteSpace(obj.DiffuseTexturePath))
            {
                var slot = Slot(obj.DiffuseTexturePath, TextureType.Diffuse, 0);
                mat.AddMaterialTexture(ref slot);
            }

            if (!string.IsNullOrWhiteSpace(obj.LightMapPath))
            {
                var slot = Slot(obj.LightMapPath, TextureType.Lightmap, 1);
                mat.AddMaterialTexture(ref slot);
            }

        }

        private static Scene BuildScene(IReadOnlyList<GeometryObject> objects)
        {
            var scene = new Scene();

            // Root node
            scene.RootNode = new Node("Root");

            // At least one material is usually needed; we’ll create one per mesh.
            // (You can customize materials/textures as needed.)
            for (int i = 0; i < objects.Count; i++)
            {
                var obj = objects[i];
                ValidateObject(obj);

                // Material
                var mat = new Material
                {
                    Name = $"{obj.Name}_Mat"
                };

                ApplyTextures(mat, obj);
                scene.Materials.Add(mat);
                int materialIndex = scene.Materials.Count - 1;

                // Mesh
                var mesh = new Mesh(obj.Name, PrimitiveType.Triangle)
                {
                    MaterialIndex = materialIndex
                };
                // Vertices
                mesh.Vertices.AddRange(obj.Positions);

                // Normals (optional)
                if (obj.Normals != null && obj.Normals.Count > 0)
                    mesh.Normals.AddRange(obj.Normals);

                // UV channel 0 (optional)
                if (obj.UVs0 != null && obj.UVs0.Count > 0)
                {
                    mesh.TextureCoordinateChannels[0].AddRange(obj.UVs0);
                    mesh.UVComponentCount[0] = 2; // we treat UV as 2D
                }
                // UV channel 1 (optional)
                if (obj.UVs1 != null && obj.UVs1.Count > 0)
                {
                    mesh.TextureCoordinateChannels[1].AddRange(obj.UVs1);
                    mesh.UVComponentCount[1] = 2;
                }

                // Faces from indices (triangles)
                for (int t = 0; t < obj.Indices.Count; t += 3)
                {
                    var a = obj.Indices[t];
                    var b = obj.Indices[t + 1];
                    var c = obj.Indices[t + 2];
                    mesh.Faces.Add(new Face(new[] { a, b, c }));
                }

                scene.Meshes.Add(mesh);
                int meshIndex = scene.Meshes.Count - 1;

                // Node for this mesh
                var node = new Node(obj.Name);
                node.MeshIndices.Add(meshIndex);
                scene.RootNode.Children.Add(node);
            }

            return scene;
        }

        private static void ValidateObject(GeometryObject obj)
        {
            if (obj.Positions.Count == 0)
                throw new InvalidDataException($"Object '{obj.Name}' has no vertex positions.");

            if (obj.Indices.Count == 0 || (obj.Indices.Count % 3) != 0)
                throw new InvalidDataException(
                    $"Object '{obj.Name}' indices must be non-empty and a multiple of 3 (triangles).");

            int vCount = obj.Positions.Count;

            // Ensure indices are in range
            for (int i = 0; i < obj.Indices.Count; i++)
            {
                int idx = obj.Indices[i];
                if (idx < 0 || idx >= vCount)
                    throw new InvalidDataException(
                        $"Object '{obj.Name}' has out-of-range index {idx} at Indices[{i}] (vertex count {vCount}).");
            }

            if (obj.Normals != null && obj.Normals.Count != 0 && obj.Normals.Count != vCount)
                throw new InvalidDataException(
                    $"Object '{obj.Name}' normals count ({obj.Normals.Count}) must match positions ({vCount}).");

            if (obj.UVs0 != null && obj.UVs0.Count != 0 && obj.UVs0.Count != vCount)
                throw new InvalidDataException(
                    $"Object '{obj.Name}' UV0 count ({obj.UVs0.Count}) must match positions ({vCount}).");
        }

        private static string InferFormatIdFromExtension(string outputPath)
        {
            var ext = Path.GetExtension(outputPath)?.TrimStart('.').ToLowerInvariant();
            if (string.IsNullOrWhiteSpace(ext))
                throw new InvalidDataException("Output path has no extension; specify formatId explicitly.");

            // Assimp format IDs usually match these short names.
            // If your build differs, pass formatId explicitly.
            return ext switch
            {
                "obj" => "obj",
                "fbx" => "fbx",
                "dae" => "collada",
                "gltf" => "gltf2",
                "glb" => "gltf2",
                "ply" => "ply",
                "stl" => "stl",
                _ => ext
            };
        }
    }
}