#version 330 core

// Generated by ChatGPT

out vec2 TexCoord;
const vec2 verts[3] = vec2[3](
    vec2(-1.0, -1.0),
    vec2( 3.0, -1.0),
    vec2(-1.0,  3.0)
);

void main() {
    TexCoord = (verts[gl_VertexID].xy + 1.0) * 0.5;
    gl_Position = vec4(verts[gl_VertexID], 0.0, 1.0);
}