#version 330 core

// Generated by ChatGPT

in vec2 TexCoord;
out vec4 FragColor;

uniform sampler2D inputTex;
uniform vec2 texelSize; // (1.0/width, 1.0/height)
uniform vec4 edgeColor;

void main() {
    vec3 c = texture(inputTex, TexCoord).rgb;

    // sample neighbors
    vec3 up    = texture(inputTex, TexCoord + vec2(0, -texelSize.y)).rgb;
    vec3 down  = texture(inputTex, TexCoord + vec2(0,  texelSize.y)).rgb;
    vec3 left  = texture(inputTex, TexCoord + vec2(-texelSize.x, 0)).rgb;
    vec3 right = texture(inputTex, TexCoord + vec2( texelSize.x, 0)).rgb;

    // detect edge by color difference
    float diff = length(right - left) + length(up - down);
    float edge = diff > 0.0005 ? 1.0 : 0.0;

    FragColor = edgeColor * edge;
}
