<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AssimpNet" Version="4.1.0" />
    <PackageReference Include="OpenTK" Version="4.9.4" />
    <PackageReference Include="OpenTK.GLControl" Version="4.0.2" />
    <PackageReference Include="SharpDX" Version="4.2.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\EditingTools\EditingTools.csproj" />
    <ProjectReference Include="..\Keybinds\Keybinds.csproj" />
    <ProjectReference Include="..\PluginApi\PluginApi.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="CSHO">
      <HintPath>..\..\..\..\Desktop\Projects\CSHO\CSHO\CSHO\bin\Debug\net6.0\CSHO.dll</HintPath>
    </Reference>
    <Reference Include="libWiiSharp">
      <HintPath>..\..\..\..\Desktop\Programme\libWiiSharp-master\bin\Release\libWiiSharp.dll</HintPath>
    </Reference>
    <Reference Include="System.Windows.Forms">
      <HintPath>..\..\..\..\..\..\Program Files\dotnet\packs\Microsoft.WindowsDesktop.App.Ref\6.0.36\ref\net6.0\System.Windows.Forms.dll</HintPath>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <Compile Update="DebugWindow.cs" />
    <Compile Update="Rendering\Custom Controls\GeometryBaseRenderer.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="Rendering\Custom Controls\GeometryBaseRendererResourcePoolManager.cs">
      <SubType>UserControl</SubType>
    </Compile>
    <Compile Update="Rendering\Custom Controls\GeometryBaseRendererUserInput.cs">
      <SubType>UserControl</SubType>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <None Update="Rendering\defaultTexture.png">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Rendering\Models\16_9_Camera.dae">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Rendering\Models\16_9_camera.obj">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Rendering\Models\Cube.obj">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Rendering\Models\Empty.dae">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Rendering\Models\Line.dae">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Rendering\Models\Sphere.obj">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Rendering\Shaders\Line\LineShader.frag">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Rendering\Shaders\Line\LineShader.vert">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Rendering\Shaders\Point\PointShader.frag">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Rendering\Shaders\Point\PointShader.vert">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Rendering\Shaders\PostProcessing\edgeDetection.frag">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Rendering\Shaders\PostProcessing\edgeDetection.vert">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Rendering\Shaders\PrimitiveModel\common.glsl">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Rendering\Shaders\PrimitiveModel\highlight.frag">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Rendering\Shaders\PrimitiveModel\highlight.vert">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Rendering\Shaders\PrimitiveModel\regular.frag">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Rendering\Shaders\PrimitiveModel\regular.vert">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Rendering\Shaders\PrimitiveModel\selection.frag">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Rendering\Shaders\PrimitiveModel\selection.vert">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Rendering\Shaders\StaticGeometry\common.glsl">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Rendering\Shaders\StaticGeometry\halo.frag">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Rendering\Shaders\StaticGeometry\halo.vert">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Rendering\Shaders\StaticGeometry\selection.frag">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Rendering\Shaders\StaticGeometry\selection.vert">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Rendering\Shaders\StaticGeometry\shader.frag">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="Rendering\Shaders\StaticGeometry\shader.vert">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
