using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace CustomControls;

public class FloatInputBox : TextBox // Generated by ChatGPT
{

    private bool isEditing = false;
    private bool isDragging = false;
    private bool dragCandidate = false;
    private Point lastMousePosition;
    private float value = 0f;
    private float increment = 0.1f; // How much the value changes per pixel drag.
    private string precisionString = "0.####";

    public float multiplier = 1f;
    public Action MouseUpCallback = () => { };
    public Action ValueChanged = () => { };

    [Browsable(true)]  // Makes the property appear in the Properties window
    [Category("Behavior")]  // Organizes it under a logical category in the Properties window
    [Description("Gets or sets the float value of the input box.")]  // Provides a description in the designer
    [DefaultValue(0f)]  // Specifies the default value for the property
    public float Value
    {
        get => value;
        set
        {
            this.value = value;
        }
    }

    [Browsable(true)]  // Makes the property appear in the Properties window
    [Category("Behavior")]  // Organizes it under a logical category in the Properties window
    [Description("Gets or sets the float value of the input box.")]  // Provides a description in the designer
    [DefaultValue(0f)]  // Specifies the default value for the property
    public float Increment
    {
        get => increment;
        set => increment = value;
    }

    public void UpdateText()
    {
        if (isEditing && !isDragging) return;
        this.Text = value.ToString(precisionString); // Display up to N decimal places
    }

    protected override void OnMouseDown(MouseEventArgs e)
    {
        
        base.OnMouseDown(e);
        if (e.Button == MouseButtons.Left)
        {
            dragCandidate = true;
            lastMousePosition = e.Location;
        }
    }

    protected override void OnMouseMove(MouseEventArgs e)
    {
        base.OnMouseMove(e);
        if (dragCandidate && !isDragging)
        {
            int deltaX = Math.Abs(e.X - lastMousePosition.X);
            if (deltaX > 3) // threshold to distinguish drag vs click
            {
                isDragging = true;
                Cursor = Cursors.SizeWE;
            }
        }

        if (isDragging)
        {
            int deltaX = e.X - lastMousePosition.X;
            lastMousePosition = e.Location;

            Value += deltaX * increment * multiplier;
            ValueChanged();
        }
    }

    protected override void OnMouseUp(MouseEventArgs e)
    {
        base.OnMouseUp(e);

        if (e.Button == MouseButtons.Left)
        {
            if (isDragging)
            {
                isDragging = false;
                Cursor = Cursors.Default;
            }

            dragCandidate = false;
        }

        MouseUpCallback();
    }

    protected override void OnEnter(EventArgs e)
    {
        base.OnEnter(e);
        isEditing = true;
    }

    protected override void OnLeave(EventArgs e)
    {
        base.OnLeave(e);
        isEditing = false;
    }

    protected override void OnKeyDown(KeyEventArgs e)
    {
        base.OnKeyDown(e);

        if (e.KeyCode == Keys.Enter)
        {
            // Force validation as if focus is changing
            
            e.Handled = true;
            e.SuppressKeyPress = true; // Prevent "ding" sound
        }

        isEditing = true; // user actively typing
    }

    protected override void OnValidating(System.ComponentModel.CancelEventArgs e)
    {
        base.OnValidating(e);
        if (!float.TryParse(this.Text, out float result))
        {
            e.Cancel = false; // Prevent loss of focus if value is invalid.
            this.Text = Value.ToString(precisionString);
        }
        else
        {
            Value = result;
            ValueChanged();
        }
    }
}