using System;
using System.Drawing;
using System.Globalization;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace Plankton.TypeConverters;

// Generated by Chatty G.
public sealed class ColorJsonConverter : JsonConverter<Color>
{
    public override Color Read(
        ref Utf8JsonReader reader,
        Type typeToConvert,
        JsonSerializerOptions options)
    {
        if (reader.TokenType == JsonTokenType.Null)
            return Color.Empty;

        string value = reader.GetString()
            ?? throw new JsonException("Color value is missing.");

        if (!value.StartsWith('#'))
            throw new JsonException(
                $"Invalid color '{value}'. Expected #AARRGGBB.");

        string hex = value[1..];

        if (hex.Length != 8)
        {
            throw new JsonException(
                $"Invalid color '{value}'. Expected #AARRGGBB.");
        }

        int argb = unchecked((int)uint.Parse(
            hex,
            NumberStyles.HexNumber,
            CultureInfo.InvariantCulture));

        return Color.FromArgb(argb);
    }

    public override void Write(
        Utf8JsonWriter writer,
        Color value,
        JsonSerializerOptions options)
    {
        if (value.IsEmpty)
        {
            writer.WriteNullValue();
            return;
        }

        writer.WriteStringValue(
            $"#{value.ToArgb():X8}");
    }
}