using System;
using System.Collections.Concurrent;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Diagnostics;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading;
using System.Threading.Tasks;
using System.Windows.Forms;
using Assimp.Configs;
using HoArchive;
using OpenTK;
using OpenTK.Graphics;
using OpenTK.Graphics.OpenGL4;
using Plankton.Rendering;
using Plankton.Rendering.Base;

// Partially generated by Chatty G.

namespace Plankton.Custom_Controls
{
    public partial class GeometryBaseRenderer : UserControl
    {
        GLControl glControl;
        public Shader shader;
        public Shader solidColorShader; // Just solid color
        public Shader selectionShader;
        public Shader edgeDetectionPPShader;

        public Frame selectionFrame; // Used to check what object was clicked
        public Frame outlineFrame; // For drawing the outline

        GenericBuffer defaultTexture; // When texture is missing, for example

        public Camera camera;

        List<Keys> pressedKeys;
        public MouseInfo mouseInfo = new();


        public float movementSpeed = 0.3f;
        float movementSpeedMax = 1;
        float movementSpeedMin = 0.05f;
        public float rotationSpeed = 0.07f;
        public bool handleCameraMovement = true;
        public bool alphaTransparency = true;

        
        // FPS Measuring
        public double fps;
        int frameCount = 0;
        DateTime lastTime = DateTime.Now;
        // Delta Timing
        DateTime lastFrameTime = DateTime.Now;
        float dt = 0;
        System.Windows.Forms.Timer drawTimer;

        private int TargetFps = 100;

        bool pauseRendering = false;

        ResourcePool resourcePool;
        public RenderHelper renderhelper;
        

        public Color4 backgroundColor = new Color4(0, 0, 0, 0);//new Color4(0.2f, 0.2f, 0.2f, 1f); // TEMP, absorb into user preferences
        public bool renderFog;

        //public Func<List<SelectableRenderable>> GetRenderables = () => { return new List<SelectableRenderable>(); };

        // Events
        public new event MouseEventHandler? MouseMove; // Mirrors the glControl events
        public new event MouseEventHandler? MouseClick;
        public new event MouseEventHandler? MouseUp;
        public event EventHandler? Render;
        public event EventHandler? PreRender;
        public event EventHandler? PostRender;

        public GeometryBaseRenderer()
        {
            InitializeComponent();

            resourcePool = new();

            pressedKeys = new List<Keys>();



        }

        public void MakeCurrent()
        {
            if(!glControl.Context.IsCurrent) glControl.MakeCurrent();
        }

        public void InitRenderer()
        {

            Debug.debugWindow.AddEntry("InitRenderer", "Initing renderer");

            glControl = new GLControl(new OpenTK.Graphics.GraphicsMode(32, 24, 8, 1));
            glControl.MakeCurrent();
            this.Controls.Add(glControl);
            glControl.Parent = this;
            glControl.Dock = DockStyle.Fill;
            glControl.Resize += glControl_Resize;
            glControl.Paint += glControl_Paint;
            //glControl.PreviewKeyDown += levelViewPanel_PreviewKeyDown;
            glControl.KeyDown += glControl_KeyDown;
            glControl.KeyUp += glControl_KeyUp;
            glControl.LostFocus += glControl_LostFocus;
            glControl.MouseDown += glControl_MouseClick;
            glControl.MouseMove += glControl_MouseMove;
            glControl.MouseUp += glControl_MouseUp;
            glControl.MouseWheel += glControl_MouseWheel;


            GL.Viewport(0, 0, this.Width, this.Height);
            camera = new Camera(3f, new Vector3(0, 0, 0), 90f, (float)this.Width / (float)this.Height, (float)Math.PI / 4.0f, (float)Math.PI / 6.0f);

            string shaderpath = "Rendering/Shaders/StaticGeometry/";
            shader = new Shader(shaderpath + "shader.vert", shaderpath + "shader.frag");
            solidColorShader = new Shader(shaderpath + "halo.vert", shaderpath + "halo.frag");
            selectionShader = new Shader(shaderpath + "selection.vert", shaderpath + "selection.frag");


            shaderpath = "Rendering/Shaders/PostProcessing/";
            edgeDetectionPPShader = new Shader(shaderpath + "edgeDetection.vert", shaderpath + "edgeDetection.frag");
            //GL.Enable(EnableCap.Blend);

            //GL.BlendFunc(BlendingFactor.SrcAlpha, BlendingFactor.OneMinusSrcAlpha);

            // Buffer used for handling selection with mouse pointer

            selectionFrame = new Frame(this.Width, this.Height);
            outlineFrame = new Frame(this.Width, this.Height);


            CreateDefaultTexture();

            // Render Stuff
            GL.ClearColor(backgroundColor);
            //GL.Enable();
            GL.Enable(EnableCap.CullFace);
            GL.Enable(EnableCap.Multisample);
            GL.Enable(EnableCap.DepthTest);
            GL.Enable(EnableCap.StencilTest);

            renderhelper = new(glControl);

            drawTimer = new();

            StartRenderLoop();
        }

        public void StartRenderLoop()
        {
            drawTimer.Interval = 1000 / TargetFps;
            drawTimer.Tick += (object sender, EventArgs e) => glControl.Invalidate();
            drawTimer.Start();
            //glControl.Invalidate();
        }

        

        public void CreateDefaultTexture()
        {
            defaultTexture = new GenericBuffer();
            defaultTexture.handle = GL.GenTexture();
            defaultTexture.hasHandle = true;

            GL.BindTexture(TextureTarget.Texture2D, defaultTexture.handle);

            // Code copied from the Texture importer
            Bitmap loadingmap = new Bitmap(Image.FromFile("Rendering/defaultTexture.png"));
            System.Drawing.Imaging.BitmapData loadingmapdata = loadingmap.LockBits(new Rectangle(0, 0, loadingmap.Width, loadingmap.Height), System.Drawing.Imaging.ImageLockMode.ReadOnly, System.Drawing.Imaging.PixelFormat.Format32bppArgb);


            GL.TexParameter(TextureTarget.Texture2D, TextureParameterName.TextureMinFilter, (int)TextureMinFilter.NearestMipmapNearest);
            GL.TexParameter(TextureTarget.Texture2D, TextureParameterName.TextureMagFilter, (int)TextureMagFilter.Nearest);
            GL.TexImage2D(TextureTarget.Texture2D, 0, PixelInternalFormat.Rgba, loadingmap.Width, loadingmap.Height,
                0, OpenTK.Graphics.OpenGL4.PixelFormat.Bgra, PixelType.UnsignedByte, loadingmapdata.Scan0);
            GL.GenerateMipmap(GenerateMipmapTarget.Texture2D);
        }

        


        public new void Focus()
        {
            glControl.Focus();
        }

        private void ResizeFramebuffer(int width, int height)
        {
            selectionFrame.Resize(width, height);
            outlineFrame.Resize(width, height);

        }


        
        private void glControl_Resize(object sender, EventArgs e)
        {
            MakeCurrent();

            ResizeFramebuffer(this.Width, this.Height);
            GL.Viewport(0, 0, this.Width, this.Height);
            camera.aspectratio = (float)this.Width / (float)this.Height;
        }







        

        

        

        private void DrawSelectedContainerOutlines()
        {

            outlineFrame.Bind();
            GL.Disable(EnableCap.Multisample);
            GL.ClearColor(0, 0, 0, 0);
            GL.Clear(ClearBufferMask.ColorBufferBit | ClearBufferMask.DepthBufferBit);
            GL.ClearColor(backgroundColor);

            solidColorShader.Use();
            solidColorShader.SetMatrix4("project", camera.GetProjectionMatrix());
            solidColorShader.SetMatrix4("view", camera.GetViewMatrix());// Matrix4.LookAt(new Vector3(0, 3, 0), Vector3.Zero, new Vector3(0,0,1)));//camera.GetViewMatrix());
            solidColorShader.SetInt("useCustomColor", 0);

            GeometryBase renderthis;
            foreach (BaseClass geom in resourcePool.aGeometryPool)
            {
                renderthis = (GeometryBase)geom;

                if (!renderthis.CanRender) { continue; }
                if (renderthis.CulledInstanceInfos.Count == 0) continue; // Unprofiled optimization (maybe)

                GL.BindVertexArray(renderthis.VertexArray.handle);
                GL.DrawElementsInstanced(OpenTK.Graphics.OpenGL4.PrimitiveType.Triangles, renderthis.elementCount, DrawElementsType.UnsignedInt, (IntPtr)0, renderthis.CulledInstanceInfos.Count);

            }
            renderhelper.SetupHighlightShader();
            renderhelper.RenderSolid();

            outlineFrame.Unbind();
            GL.Enable(EnableCap.Multisample);

            GL.Disable(EnableCap.DepthTest);

            edgeDetectionPPShader.Use();
            GL.ActiveTexture(TextureUnit.Texture0);
            outlineFrame.BindTexture();
            edgeDetectionPPShader.SetInt("inputTex", 0);
            edgeDetectionPPShader.SetFloat2("texelSize", 1f / Width, 1f / Height);
            edgeDetectionPPShader.SetColor4("edgeColor", GlobalRenderSettings.highlightColor);

            GL.Enable(EnableCap.Blend);
            GL.BlendFunc(BlendingFactor.SrcAlpha, BlendingFactor.OneMinusSrcAlpha);

            GL.DrawArrays(OpenTK.Graphics.OpenGL4.PrimitiveType.Triangles, 0, 3);

            GL.LineWidth(1);
            renderhelper.SetupHighlightShader(true);
            renderhelper.RenderNonSolid();

            GL.Disable(EnableCap.Blend);
            GL.Enable(EnableCap.DepthTest);
        }

        

        private void DrawSelectionBuffer()
        {
            selectionFrame.Bind();
            GL.Disable(EnableCap.Multisample);
            GL.ClearColor(0, 0, 0, 0);
            GL.Clear(ClearBufferMask.ColorBufferBit | ClearBufferMask.DepthBufferBit | ClearBufferMask.StencilBufferBit);
            GL.ClearColor(backgroundColor);

            selectionShader.Use();

            selectionShader.SetMatrix4("project", camera.GetProjectionMatrix());
            selectionShader.SetMatrix4("view", camera.GetViewMatrix());// Matrix4.LookAt(new Vector3(0, 3, 0), Vector3.Zero, new Vector3(0,0,1)));//camera.GetViewMatrix());


            GeometryBase renderthis;
            foreach (BaseClass geom in resourcePool.aGeometryPool)
            {
                renderthis = (GeometryBase)geom;

                renderthis.Render();
            }

            // Uses it's own shaders
            /*int attr = 0;
            foreach(EditableContainer container in editableContainers)
            {
                attr++;
                if (container.isInstanced) { continue; }
                if (!ContainerTypeIsChecked(container.GetType())) { continue; }

                container.RenderToSelectionBuffer(attr);
            }*/
            GL.LineWidth(20);
            renderhelper.SetupSelectionShader();
            renderhelper.Render();

            selectionFrame.Unbind();
            GL.Enable(EnableCap.Multisample);


        }

        private void SetLightKitUniforms() // Make more general! Or set up system for seperated rendering. This isn't very nice!
        {



            List<TOCEntry> lightkits = resourcePool.lightKitPool;

            if (lightkits.Count > 10) { Debug.debugWindow.AddEntry("SetLightKitUniforms", "Warning: More than 10 lightkits"); return; }

            List<ulong> lookupIDs = new();
            foreach (TOCEntry entry in lightkits)
            {
                lookupIDs.Add(((SB09WiiAsset.LightKit)entry.entity).lookupTex);
            }

            List<BaseClass> lookupTextures = resourcePool.GetAssetsFromPool(resourcePool.aTexturePool, lookupIDs);


            int[] samplers = new int[10];
            for (int i = 0; i < lightkits.Count; i++)
            {
                if (lookupTextures[i] == null) continue;
                TextureBase tex = (TextureBase)lookupTextures[i];
                GL.ActiveTexture(TextureUnit.Texture6 + i);
                GL.BindTexture(TextureTarget.Texture2D, tex.buffer.handle);

                samplers[i] = 6 + i;

            }

            shader.SetInts("lightkitLookups", samplers);

            for (int i = 0; i < lightkits.Count; i++)
            {

                SB09WiiAsset.LightKit kit = (SB09WiiAsset.LightKit)lightkits[i].entity;

                shader.SetVector3($"lightkits[{i}].light1", VectorMath.DirectionFromYawPitchRoll(kit.dir.element0.orientation.GetVector3()));
                shader.SetVector3($"lightkits[{i}].light2", VectorMath.DirectionFromYawPitchRoll(kit.dir.element1.orientation.GetVector3()));
                shader.SetVector3($"lightkits[{i}].light3", VectorMath.DirectionFromYawPitchRoll(kit.dir.element2.orientation.GetVector3()));
                shader.SetVector3($"lightkits[{i}].light4", VectorMath.DirectionFromYawPitchRoll(kit.dir.element3.orientation.GetVector3()));

                FloatColorRGB vec = kit.dir.element2.color;
                shader.SetVector3($"lightkits[{i}].color3", new System.Numerics.Vector3(vec.r, vec.g, vec.b));
                vec = kit.dir.element3.color;
                shader.SetVector3($"lightkits[{i}].color4", new System.Numerics.Vector3(vec.r, vec.g, vec.b));

                vec = kit.ambientColor;
                shader.SetVector3($"lightkits[{i}].ambientcolor", new System.Numerics.Vector3(vec.r, vec.g, vec.b));
            }
        }

        private void SetupTextures(GeometryBase renderthis)
        {
            GL.ActiveTexture(TextureUnit.Texture0);
            if (renderthis.textureSet.diffuseMap.hasHandle) { GL.BindTexture(TextureTarget.Texture2D, renderthis.textureSet.diffuseMap.handle); }
            else { GL.BindTexture(TextureTarget.Texture2D, defaultTexture.handle); }

            GL.ActiveTexture(TextureUnit.Texture1);
            if (renderthis.textureSet.lightMap.hasHandle)
            {
                GL.BindTexture(TextureTarget.Texture2D, renderthis.textureSet.lightMap.handle);
            }

            GL.ActiveTexture(TextureUnit.Texture2);
            if (renderthis.textureSet.environmentMap.hasHandle)
            {
                GL.BindTexture(TextureTarget.Texture2D, renderthis.textureSet.environmentMap.handle);
            }
            GL.ActiveTexture(TextureUnit.Texture3);
            if (renderthis.textureSet.diffuseMap1.hasHandle)
            {
                GL.BindTexture(TextureTarget.Texture2D, renderthis.textureSet.diffuseMap1.handle);
            }
            GL.ActiveTexture(TextureUnit.Texture4);
            if (renderthis.textureSet.blendMap.hasHandle)
            {
                GL.BindTexture(TextureTarget.Texture2D, renderthis.textureSet.blendMap.handle);
            }
        }

        private void SetupFogUniforms()
        {
            if (resourcePool.fogPool.Count() <= 0)
            {
                shader.SetInt("fog.fogMode", 0);
                return;
            }
            SB09WiiAsset.Fog fog = (SB09WiiAsset.Fog)resourcePool.fogPool[0].entity;

            shader.SetFloat("fog.start", fog.start);
            shader.SetFloat("fog.end", fog.end);
            shader.SetInt("fog.fogMode", renderFog ? (int)fog.mode : 0);
            shader.SetColor4("fog.fogColor", new Color4(fog.color.r, fog.color.g, fog.color.b, fog.color.a));
        }

        private void DrawGeometryPool()
        {
            shader.Use();

            shader.SetMatrix4("project", camera.GetProjectionMatrix());
            shader.SetMatrix4("view", camera.GetViewMatrix());// Matrix4.LookAt(new Vector3(0, 3, 0), Vector3.Zero, new Vector3(0,0,1)));//camera.GetViewMatrix());
            shader.SetInt("diffuseMap", 0);
            shader.SetInt("lightMap", 1);
            shader.SetInt("environmentMap", 2);
            shader.SetInt("diffuseMap1", 3);
            shader.SetInt("blendMap", 4);

            SetupFogUniforms();
            SetLightKitUniforms();

            GeometryBase renderthis;
            foreach (BaseClass geom in resourcePool.aGeometryPool)
            {
                renderthis = (GeometryBase)geom;

                if (!renderthis.CanRender || (alphaTransparency && renderthis.isTransparent)) continue;//) { continue; }//
                if (renderthis.CulledInstanceInfos.Count == 0) continue;

                shader.SetInt("Flags", renderthis.Flags);
                shader.SetInt("ShaderOpsFlags", (int)renderthis.ShaderOpsFlags);
                shader.SetColor4("ambientScale", renderthis.ambientScale);
                shader.SetFloat("environmentScale", renderthis.environmentScale);

                SetupTextures(renderthis);
                

                renderthis.Render();
            }

            if (!alphaTransparency) return;
            // ALPHA TRANSPARENCY
            //return; // Disabled for now because of performance reasons. Optimize via compute shader perhaps?
            List<GeometryBase> transparentGeometries = new();
            foreach (BaseClass geom in resourcePool.aGeometryPool)
            {
                renderthis = (GeometryBase)geom;

                if (!renderthis.CanRender || !renderthis.isTransparent) { continue; }

                transparentGeometries.Add(renderthis);
            }

            List<InstanceDepth> depthList = new List<InstanceDepth>();

            for (int geometryIndex = 0; geometryIndex < transparentGeometries.Count; geometryIndex++)
            {
                GeometryBase geometry = transparentGeometries[geometryIndex];
                for (int instanceIndex = 0; instanceIndex < geometry.CulledInstanceInfos.Count; instanceIndex++)
                {
                    Matrix4 instanceMatrix = ConverterTools.ToOpenTK(geometry.CulledInstanceInfos[instanceIndex].matrix);
                    instanceMatrix.Transpose();
                    OpenTK.Vector3 instancePosition = (instanceMatrix * new OpenTK.Vector4(ConverterTools.ToOpenTK(geometry.GetAABBCenter()), 1)).Xyz;

                    float depth = OpenTK.Vector3.Distance(camera.GetPosition(), instancePosition);

                    depthList.Add(new InstanceDepth(geometryIndex, instanceIndex, depth));
                }
            }
            // Sort via depth
            depthList.Sort((a, b) => b.Depth.CompareTo(a.Depth));

            renderhelper.EnableBlending();

            foreach (InstanceDepth instanceDepth in depthList)
            {
                renderthis = transparentGeometries[instanceDepth.GeometryIndex];

                shader.SetInt("Flags", renderthis.Flags);
                shader.SetInt("ShaderOpsFlags", (int)renderthis.ShaderOpsFlags);
                shader.SetColor4("ambientScale", renderthis.ambientScale);
                shader.SetFloat("environmentScale", renderthis.environmentScale);

                SetupTextures(renderthis);

                renderthis.RenderInstance(instanceDepth.InstanceIndex);
            }

            renderhelper.DisableBlending();
        }

        public int ReadSelectionIndex(int x, int y)
        {
            MakeCurrent();
            DrawSelectionBuffer();

            selectionFrame.Bind();
            GL.ReadBuffer(ReadBufferMode.ColorAttachment0);

            byte[] pixels = new byte[4];
            GL.ReadPixels(x, Height - y, 1, 1, OpenTK.Graphics.OpenGL4.PixelFormat.Rgba, PixelType.UnsignedByte, pixels);
            selectionFrame.Unbind();

            int index = 0;
            for (int i = 0; i < 3; i++)
            {
                index |= pixels[i] << (i * 8);
            }


            return index - 1;
        }


        public HashSet<uint> ReadSelectionIds(Rectangle rectangle)
        {
            int x = Math.Clamp(
                rectangle.Left,
                0,
                glControl.ClientSize.Width - 1);

            int top = Math.Clamp(
                rectangle.Top,
                0,
                glControl.ClientSize.Height - 1);

            int right = Math.Clamp(
                rectangle.Right,
                0,
                glControl.ClientSize.Width);

            int bottom = Math.Clamp(
                rectangle.Bottom,
                0,
                glControl.ClientSize.Height);

            int width = right - x;
            int height = bottom - top;

            if (width <= 0 || height <= 0)
                return new HashSet<uint>();

            int requiredLength = width * height;

            byte[] _selectionPixels = new byte[4 * requiredLength];

            int openGlY =
                glControl.ClientSize.Height - bottom;

            MakeCurrent();
            DrawSelectionBuffer();

            selectionFrame.Bind();
            GL.ReadBuffer(ReadBufferMode.ColorAttachment0);

            GL.ReadPixels(
                x,
                openGlY,
                width,
                height,
                OpenTK.Graphics.OpenGL4.PixelFormat.Rgba, PixelType.UnsignedByte, _selectionPixels);

            selectionFrame.Unbind();

            var selectedIds = new HashSet<uint>();

            for (int index = 0; index < requiredLength; index++)
            {
                int id = 0;
                for (int i = 0; i < 3; i++)
                {
                    id |= _selectionPixels[i + index * 4] << (i * 8);
                }
                // Assuming zero means "nothing selected."
                if (id != 0)
                    selectedIds.Add((uint)id-1);
            }

            return selectedIds;
        }


        private void CullaGeometry(GeometryBase geom)
        {
            System.Numerics.Vector3 center = geom.GetBoundSphereCenter();
            float radius = geom.GetBoundSphereRadius();

            geom.CulledInstanceInfos.Clear();
            foreach (InstanceInfo info in geom.InstanceInfos)
            {
                System.Numerics.Vector4 worldcenter = System.Numerics.Vector4.Transform(new System.Numerics.Vector4(center, 1), info.matrix);
                float worldradius = radius * Math.Max(
                    new System.Numerics.Vector3(info.matrix.M11, info.matrix.M12, info.matrix.M13).Length(),
                    Math.Max(

                    new System.Numerics.Vector3(info.matrix.M21, info.matrix.M22, info.matrix.M23).Length(),
                    new System.Numerics.Vector3(info.matrix.M31, info.matrix.M32, info.matrix.M33).Length()));
                //geom.CulledInstanceInfos.Add(info);
                if (camera.frustum.isSphereInsideFrustum(new OpenTK.Vector3(worldcenter.X, worldcenter.Y, worldcenter.Z), worldradius))
                    geom.CulledInstanceInfos.Add(info);

            }

            /*ConcurrentBag<RenderingInternal.InstanceInfo> infos = new ConcurrentBag<RenderingInternal.InstanceInfo>();

            geom.CulledInstanceInfos.Clear();
            Parallel.ForEach(geom.InstanceInfos, info =>
            {

                System.Numerics.Vector4 worldcenter = System.Numerics.Vector4.Transform(new System.Numerics.Vector4(center, 1), info.matrix);
                float worldradius = radius * Math.Max(
                    new System.Numerics.Vector3(info.matrix.M11, info.matrix.M12, info.matrix.M13).Length(),
                    Math.Max(

                    new System.Numerics.Vector3(info.matrix.M21, info.matrix.M22, info.matrix.M23).Length(),
                    new System.Numerics.Vector3(info.matrix.M31, info.matrix.M32, info.matrix.M33).Length()));
                //geom.CulledInstanceInfos.Add(info);
                if (camera.frustum.isSphereInsideFrustum(new OpenTK.Vector3(worldcenter.X, worldcenter.Y, worldcenter.Z), worldradius)) infos.Add(info);
            });

            geom.CulledInstanceInfos = infos.ToList();*/
        }

        private void CullGeometryPool()
        {
            /*Parallel.ForEach(resourcePool.aGeometryPool, entry =>
            {
                CullaGeometry((GeometryBase)entry);
            });*/

            foreach(BaseClass entry in resourcePool.aGeometryPool)
            {
                CullaGeometry((GeometryBase)entry);
            }
        }

        private void CullAndBufferContainers()
        {
            // internal geometry (geometry that is defined inside of the archive, previously called "instanced geometry")
            CullGeometryPool();
            BufferAllGeometryInstances();

        }

        private void DrawContainers()
        {
            // Instanced geometry
            DrawGeometryPool();

            // Transparent
            renderhelper.EnableBlending();

            GL.LineWidth(1);
            renderhelper.SetupRegularShader();
            renderhelper.Render();
            //Debug.debugWindow.AddEntry("DrawContainers", RenderHelper.models.Sphere.instances.Count);

            renderhelper.DisableBlending();
        }

        private void glControl_Paint(object sender, PaintEventArgs e)
        {
            if (pauseRendering) { return; }

            DateTime now = DateTime.Now;
            TimeSpan elapsedTime = now - lastFrameTime;

            dt = (float)elapsedTime.TotalSeconds;
            lastFrameTime = now;

            MakeCurrent();

            PreRender?.Invoke(this, EventArgs.Empty);

            var stopwatch = Stopwatch.StartNew();
            HandleUserInput();
            double userinputms = stopwatch.Elapsed.TotalMilliseconds;

            //if (camera.frustum.isSphereInsideFrustum(new OpenTK.Vector3(2, 0, 0), 0)) Debug.debugWindow.AddEntry("Paint", "isinside!");


            
            GL.Clear(ClearBufferMask.ColorBufferBit | ClearBufferMask.DepthBufferBit | ClearBufferMask.StencilBufferBit);


            camera.UpdateViewProj();
            renderhelper.view = camera.GetViewMatrix();
            renderhelper.projection = camera.GetProjectionMatrix();

            stopwatch.Restart();
            // Cull anything that isn't going to be on screen and buffer (in-archive geometry only atm)
            CullAndBufferContainers();
            double cullandbufferms = stopwatch.Elapsed.TotalMilliseconds;


            /*stopwatch.Restart();
            // Draw buffer that's used for click selection
            DrawSelectionBuffer();
            double selectionbufferms = stopwatch.Elapsed.TotalMilliseconds;
            */
            stopwatch.Restart();
            // Draw every editable container
            DrawContainers();
            double regularbufferms = stopwatch.Elapsed.TotalMilliseconds;

            Render?.Invoke(this, EventArgs.Empty);

            //int dbg = 0;
            //Debug.debugWindow.AddEntry("Paint", camera.frustum.planes[dbg].normal.ToString() + ", " + camera.frustum.planes[dbg].D.ToString());
            //RenderHelper.RenderLine(System.Numerics.Vector3.Zero, ConverterTools.FromOpenTK(camera.frustum.planes[dbg].normal), Color4.White, 1);
            // Draw outline

            stopwatch.Restart();
            DrawSelectedContainerOutlines();
            double outlinebufferms = stopwatch.Elapsed.TotalMilliseconds;

            

            glControl.SwapBuffers();    // Display the result.


            PostRender?.Invoke(this, EventArgs.Empty);
            //drawTimer.Stop();


            /*DateTime _now = DateTime.Now;
            TimeSpan _elapsedTime = _now - lastTime;
            if(_elapsedTime.TotalSeconds > 1.0)
            {
                Debug.debugWindow.AddEntry("Draw", DebugEntryType.NORMAL, userinputms, cullandbufferms, regularbufferms, outlinebufferms);
            }*/
            CalculateFPS();


        }

        public void DrawGrid()
        {
            //RenderHelper.RenderLine(System.Numerics.Vector3.UnitX * -1000f, System.Numerics.Vector3.UnitX * 1000f, Color4.Red, 1);
            //RenderHelper.RenderLine(System.Numerics.Vector3.UnitY * -1000f, System.Numerics.Vector3.UnitY * 1000f, Color4.Green, 1);
            //RenderHelper.RenderLine(System.Numerics.Vector3.UnitZ * -1000f, System.Numerics.Vector3.UnitZ * 1000f, Color4.Blue, 1);
            int N = 10;

            renderhelper.RenderLine(System.Numerics.Vector3.UnitX * -N, System.Numerics.Vector3.UnitX * N, Color4.Red, 1);
            renderhelper.RenderLine(System.Numerics.Vector3.UnitZ * -N, System.Numerics.Vector3.UnitZ * N, Color4.Blue, 1);


            for (int x = -N; x <= N; x++)
            {
                renderhelper.RenderLine(System.Numerics.Vector3.UnitX * -N + x * System.Numerics.Vector3.UnitZ, System.Numerics.Vector3.UnitX * N + x * System.Numerics.Vector3.UnitZ, Color4.Gray, 1);
            }
            for (int x = -N; x <= N; x++)
            {
                renderhelper.RenderLine(System.Numerics.Vector3.UnitZ * -N + x * System.Numerics.Vector3.UnitX, System.Numerics.Vector3.UnitZ * N + x * System.Numerics.Vector3.UnitX, Color4.Gray, 1);
            }
        }


        private void CalculateFPS()
        {
            frameCount++;

            // Calculate the FPS every second
            DateTime now = DateTime.Now;
            TimeSpan elapsedTime = now - lastTime;

            

            if (elapsedTime.TotalSeconds >= 1.0)
            {
                // FPS calculation
                fps = frameCount / elapsedTime.TotalSeconds;

                //Application.DoEvents();
                //Debug.debugWindow.AddEntry("CalculateFPS", type:DebugEntryType.NORMAL, dthistory.ToArray());
                
                // Reset for the next second
                frameCount = 0;
                lastTime = now;
            }
        }
    }

    public struct InstanceDepth
    {
        public int GeometryIndex;
        public int InstanceIndex;
        public float Depth;

        public InstanceDepth(int geometryIndex, int instanceIndex, float depth)
        {
            GeometryIndex = geometryIndex;
            InstanceIndex = instanceIndex;
            Depth = depth;
        }
    }
}
