using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Drawing;
using System.Globalization;
using System.Reflection;
using System.Windows.Forms;

// Generated by Chatty G. PT thanks a lot

namespace Plankton.Custom_Controls
{
    /// <summary>
    /// A complete, reusable WinForms collection editor. Drop it onto a Form,
    /// then call Bind(model, nameof(model.Items)) or assign Items directly.
    /// </summary>
    [ToolboxItem(true)]
    [DefaultEvent(nameof(CollectionChanged))]
    [DefaultProperty(nameof(CollectionPropertyName))]
    public class CollectionEditorControl : UserControl
    {
        private readonly SplitContainer _splitContainer;
        private readonly ToolStrip _toolStrip;
        private readonly ToolStripButton _addButton;
        private readonly ToolStripButton _removeButton;
        private readonly ToolStripButton _moveUpButton;
        private readonly ToolStripButton _moveDownButton;
        private readonly ToolStripButton _refreshButton;
        private readonly ToolStripLabel _countLabel;
        private readonly ListBox _itemsList;
        private readonly PropertyGrid _propertyGrid;
        private readonly Label _emptyLabel;

        private IList _items;
        private object _selectedObject;
        private string _collectionPropertyName = string.Empty;
        private Type _declaredCollectionType;
        private Type _inferredItemType;
        private Type _itemTypeOverride;
        private Func<object> _itemFactory;
        private IBindingList _bindingList;
        private INotifyCollectionChanged _notifyCollection;
        private INotifyPropertyChanged _selectedItemNotifier;
        private bool _refreshing;
        private int _internalChangeDepth;
        private string _displayMember = string.Empty;
        private bool _allowAdd = true;
        private bool _allowRemove = true;
        private bool _allowReorder = true;
        private bool _allowPropertyEditing = true;
        private bool _confirmRemove;
        private bool _showOperationErrors = true;

        public CollectionEditorControl()
        {
            SetStyle(ControlStyles.AllPaintingInWmPaint |
                     ControlStyles.OptimizedDoubleBuffer |
                     ControlStyles.ResizeRedraw, true);

            MinimumSize = new Size(320, 180);
            Size = new Size(720, 420);

            _splitContainer = new SplitContainer
            {
                Dock = DockStyle.Fill,
                FixedPanel = FixedPanel.Panel1,
                SplitterDistance = 250,
                Panel1MinSize = 140,
                Panel2MinSize = 140
            };

            _toolStrip = new ToolStrip
            {
                Dock = DockStyle.Top,
                GripStyle = ToolStripGripStyle.Hidden,
                RenderMode = ToolStripRenderMode.System,
                Padding = new Padding(2)
            };

            _addButton = CreateButton("Add", "Add a new item (Insert)");
            _removeButton = CreateButton("Remove", "Remove the selected item (Delete)");
            _moveUpButton = CreateButton("Up", "Move the selected item up (Ctrl+Up)");
            _moveDownButton = CreateButton("Down", "Move the selected item down (Ctrl+Down)");
            _refreshButton = CreateButton("Refresh", "Reload the list from the collection (F5)");
            _countLabel = new ToolStripLabel
            {
                Alignment = ToolStripItemAlignment.Right,
                Text = "0 items"
            };

            _toolStrip.Items.Add(_addButton);
            _toolStrip.Items.Add(_removeButton);
            _toolStrip.Items.Add(new ToolStripSeparator());
            _toolStrip.Items.Add(_moveUpButton);
            _toolStrip.Items.Add(_moveDownButton);
            _toolStrip.Items.Add(new ToolStripSeparator());
            _toolStrip.Items.Add(_refreshButton);
            _toolStrip.Items.Add(_countLabel);

            _itemsList = new ListBox
            {
                Dock = DockStyle.Fill,
                IntegralHeight = false,
                FormattingEnabled = true,
                HorizontalScrollbar = true
            };

            _emptyLabel = new Label
            {
                Dock = DockStyle.Fill,
                TextAlign = ContentAlignment.MiddleCenter,
                Text = "No collection assigned",
                ForeColor = SystemColors.GrayText,
                BackColor = SystemColors.Window
            };

            _propertyGrid = new PropertyGrid
            {
                Dock = DockStyle.Fill,
                HelpVisible = true,
                ToolbarVisible = true,
                PropertySort = PropertySort.CategorizedAlphabetical
            };

            Panel leftPanel = new Panel { Dock = DockStyle.Fill };
            leftPanel.Controls.Add(_itemsList);
            leftPanel.Controls.Add(_emptyLabel);
            leftPanel.Controls.Add(_toolStrip);

            _splitContainer.Panel1.Controls.Add(leftPanel);
            _splitContainer.Panel2.Controls.Add(_propertyGrid);
            Controls.Add(_splitContainer);

            _addButton.Click += delegate { AddItem(); };
            _removeButton.Click += delegate { RemoveSelectedItem(); };
            _moveUpButton.Click += delegate { MoveSelectedItem(-1); };
            _moveDownButton.Click += delegate { MoveSelectedItem(1); };
            _refreshButton.Click += delegate { RefreshItems(true); };

            _itemsList.SelectedIndexChanged += ItemsList_SelectedIndexChanged;
            _itemsList.Format += ItemsList_Format;
            _itemsList.KeyDown += ItemsList_KeyDown;
            _itemsList.DoubleClick += delegate
            {
                if (_propertyGrid.SelectedObject != null)
                    _propertyGrid.Focus();
            };

            _propertyGrid.PropertyValueChanged += PropertyGrid_PropertyValueChanged;
            EnabledChanged += delegate { UpdateCommandState(); };

            UpdateViewState();
        }

        /// <summary>
        /// The collection being edited. List&lt;T&gt;, BindingList&lt;T&gt; and other
        /// collections implementing non-generic IList are supported.
        /// </summary>
        [Browsable(false)]
        [DesignerSerializationVisibility(DesignerSerializationVisibility.Hidden)]
        public IList Items
        {
            get { return _items; }
            set
            {
                _selectedObject = null;
                _collectionPropertyName = string.Empty;
                _declaredCollectionType = value == null ? null : value.GetType();
                SetItems(value);
            }
        }

        /// <summary>
        /// An object containing the collection property named by CollectionPropertyName.
        /// If it contains exactly one IList property, that property is selected automatically.
        /// </summary>
        [Browsable(false)]
        [DesignerSerializationVisibility(DesignerSerializationVisibility.Hidden)]
        public object SelectedObject
        {
            get { return _selectedObject; }
            set
            {
                _selectedObject = value;
                ResolveCollectionFromSelectedObject();
            }
        }

        /// <summary>
        /// Name of the IList property on SelectedObject. Set this before or after SelectedObject.
        /// </summary>
        [Category("Data")]
        [Description("Name of the list property to edit on SelectedObject.")]
        [DefaultValue("")]
        public string CollectionPropertyName
        {
            get { return _collectionPropertyName; }
            set
            {
                string newValue = value ?? string.Empty;
                if (string.Equals(_collectionPropertyName, newValue, StringComparison.Ordinal))
                    return;

                _collectionPropertyName = newValue;
                ResolveCollectionFromSelectedObject();
            }
        }

        /// <summary>
        /// Optional explicit item type. Normally inferred automatically from List&lt;T&gt;.
        /// </summary>
        [Browsable(false)]
        [DesignerSerializationVisibility(DesignerSerializationVisibility.Hidden)]
        public Type ItemType
        {
            get { return _itemTypeOverride ?? _inferredItemType; }
            set
            {
                _itemTypeOverride = value;
                UpdateCommandState();
            }
        }

        /// <summary>
        /// Optional custom factory. Not needed for normal classes with a public parameterless constructor.
        /// </summary>
        [Browsable(false)]
        [DesignerSerializationVisibility(DesignerSerializationVisibility.Hidden)]
        public Func<object> ItemFactory
        {
            get { return _itemFactory; }
            set
            {
                _itemFactory = value;
                UpdateCommandState();
            }
        }

        [Browsable(false)]
        [DesignerSerializationVisibility(DesignerSerializationVisibility.Hidden)]
        public object SelectedItem
        {
            get { return _itemsList.SelectedItem; }
        }

        [Browsable(false)]
        [DesignerSerializationVisibility(DesignerSerializationVisibility.Hidden)]
        public int SelectedIndex
        {
            get { return _itemsList.SelectedIndex; }
            set
            {
                if (value < -1 || value >= _itemsList.Items.Count)
                    throw new ArgumentOutOfRangeException(nameof(value));
                _itemsList.SelectedIndex = value;
            }
        }

        [Category("Appearance")]
        [Description("Property used as the text shown for each item. Leave empty to use ToString().")]
        [DefaultValue("")]
        public string DisplayMember
        {
            get { return _displayMember; }
            set
            {
                _displayMember = value ?? string.Empty;
                _itemsList.Refresh();
            }
        }

        [Category("Behavior")]
        [DefaultValue(true)]
        public bool AllowAdd
        {
            get { return _allowAdd; }
            set
            {
                _allowAdd = value;
                UpdateCommandState();
            }
        }

        [Category("Behavior")]
        [DefaultValue(true)]
        public bool AllowRemove
        {
            get { return _allowRemove; }
            set
            {
                _allowRemove = value;
                UpdateCommandState();
            }
        }

        [Category("Behavior")]
        [DefaultValue(true)]
        public bool AllowReorder
        {
            get { return _allowReorder; }
            set
            {
                _allowReorder = value;
                UpdateCommandState();
            }
        }

        [Category("Behavior")]
        [DefaultValue(true)]
        public bool AllowPropertyEditing
        {
            get { return _allowPropertyEditing; }
            set
            {
                _allowPropertyEditing = value;
                _propertyGrid.Enabled = value;
            }
        }

        [Category("Behavior")]
        [DefaultValue(false)]
        public bool ConfirmRemove
        {
            get { return _confirmRemove; }
            set { _confirmRemove = value; }
        }

        [Category("Behavior")]
        [Description("Show a message box when an add, remove, or move operation fails.")]
        [DefaultValue(true)]
        public bool ShowOperationErrors
        {
            get { return _showOperationErrors; }
            set { _showOperationErrors = value; }
        }

        [Category("Appearance")]
        [DefaultValue(true)]
        public bool PropertyGridToolbarVisible
        {
            get { return _propertyGrid.ToolbarVisible; }
            set { _propertyGrid.ToolbarVisible = value; }
        }

        [Category("Appearance")]
        [DefaultValue(true)]
        public bool PropertyGridHelpVisible
        {
            get { return _propertyGrid.HelpVisible; }
            set { _propertyGrid.HelpVisible = value; }
        }

        [Category("Appearance")]
        [DefaultValue(PropertySort.CategorizedAlphabetical)]
        public PropertySort PropertySort
        {
            get { return _propertyGrid.PropertySort; }
            set { _propertyGrid.PropertySort = value; }
        }

        [Category("Layout")]
        [DefaultValue(250)]
        public int ListPanelWidth
        {
            get { return _splitContainer.SplitterDistance; }
            set
            {
                int minimum = _splitContainer.Panel1MinSize;
                int maximum = Math.Max(minimum, Width - _splitContainer.Panel2MinSize - _splitContainer.SplitterWidth);
                _splitContainer.SplitterDistance = Math.Max(minimum, Math.Min(value, maximum));
            }
        }

        public event EventHandler CollectionChanged;
        public event EventHandler SelectedItemChanged;
        public event PropertyValueChangedEventHandler ItemPropertyValueChanged;
        public event EventHandler<CollectionItemEventArgs> ItemAdded;
        public event EventHandler<CollectionItemEventArgs> ItemRemoved;
        public event EventHandler<CollectionEditorOperationFailedEventArgs> OperationFailed;
        public event EventHandler<CollectionItemCreatingEventArgs> ItemCreating;

        /// <summary>
        /// Binds the control to a list property on an object. This is the normal one-line setup.
        /// </summary>
        public void Bind(object owner, string collectionPropertyName)
        {
            if (owner == null)
                throw new ArgumentNullException(nameof(owner));
            if (string.IsNullOrWhiteSpace(collectionPropertyName))
                throw new ArgumentException("A collection property name is required.", nameof(collectionPropertyName));

            _collectionPropertyName = collectionPropertyName;
            _selectedObject = owner;
            ResolveCollectionFromSelectedObject();
        }

        /// <summary>
        /// Binds the control directly to a collection.
        /// </summary>
        public void Bind(IList items)
        {
            if (items == null)
                throw new ArgumentNullException(nameof(items));

            Items = items;
        }

        /// <summary>
        /// Binds directly and supplies an explicit factory for abstract types or classes
        /// without a public parameterless constructor.
        /// </summary>
        public void Bind(IList items, Func<object> itemFactory)
        {
            if (items == null)
                throw new ArgumentNullException(nameof(items));
            if (itemFactory == null)
                throw new ArgumentNullException(nameof(itemFactory));

            Items = items;
            ItemFactory = itemFactory;
        }

        public void AddItem()
        {
            if (!CanModifyCollection() || !_allowAdd)
                return;

            try
            {
                object newItem = CreateNewItem();
                if (newItem == null && IsNonNullableValueType(ItemType))
                    throw new InvalidOperationException("The item factory returned null for a non-nullable value type.");

                int newIndex;
                BeginInternalCollectionChange();
                try
                {
                    newIndex = _items.Add(newItem);
                }
                finally
                {
                    EndInternalCollectionChange();
                }

                RefreshItems(false);
                if (newIndex < 0 || newIndex >= _itemsList.Items.Count)
                    newIndex = _itemsList.Items.Count - 1;
                _itemsList.SelectedIndex = newIndex;

                OnItemAdded(new CollectionItemEventArgs(newItem, newIndex));
                OnCollectionChanged(EventArgs.Empty);
            }
            catch (Exception ex)
            {
                HandleOperationFailure("add an item", ex);
            }
        }

        public void RemoveSelectedItem()
        {
            int index = _itemsList.SelectedIndex;
            if (!CanModifyCollection() || !_allowRemove || index < 0)
                return;

            object item = _items[index];

            if (_confirmRemove)
            {
                DialogResult result = MessageBox.Show(
                    FindForm(),
                    "Remove the selected item?",
                    "Remove item",
                    MessageBoxButtons.YesNo,
                    MessageBoxIcon.Question,
                    MessageBoxDefaultButton.Button2);

                if (result != DialogResult.Yes)
                    return;
            }

            try
            {
                BeginInternalCollectionChange();
                try
                {
                    _items.RemoveAt(index);
                }
                finally
                {
                    EndInternalCollectionChange();
                }

                RefreshItems(false);
                if (_itemsList.Items.Count > 0)
                    _itemsList.SelectedIndex = Math.Min(index, _itemsList.Items.Count - 1);

                OnItemRemoved(new CollectionItemEventArgs(item, index));
                OnCollectionChanged(EventArgs.Empty);
            }
            catch (Exception ex)
            {
                HandleOperationFailure("remove the selected item", ex);
            }
        }

        public void MoveSelectedItemUp()
        {
            MoveSelectedItem(-1);
        }

        public void MoveSelectedItemDown()
        {
            MoveSelectedItem(1);
        }

        public void RefreshCollection()
        {
            RefreshItems(true);
        }

        protected virtual object CreateNewItem()
        {
            Type itemType = ItemType;
            CollectionItemCreatingEventArgs args = new CollectionItemCreatingEventArgs(itemType);
            OnItemCreating(args);

            if (args.Cancel)
                throw new OperationCanceledException("Item creation was cancelled.");
            if (args.Item != null)
                return args.Item;
            if (_itemFactory != null)
                return _itemFactory();

            if (itemType == null)
            {
                throw new InvalidOperationException(
                    "The item type could not be inferred. Set ItemType or ItemFactory before adding items.");
            }

            Type nullableUnderlyingType = Nullable.GetUnderlyingType(itemType);
            if (nullableUnderlyingType != null)
                return null;

            if (itemType == typeof(string))
                return string.Empty;

            if (itemType.IsValueType)
                return Activator.CreateInstance(itemType);

            if (itemType.IsInterface || itemType.IsAbstract)
            {
                throw new InvalidOperationException(
                    "Cannot create an instance of " + itemType.FullName +
                    ". Assign ItemFactory to create concrete instances.");
            }

            ConstructorInfo constructor = itemType.GetConstructor(Type.EmptyTypes);
            if (constructor == null)
            {
                throw new InvalidOperationException(
                    itemType.FullName +
                    " does not have a public parameterless constructor. Assign ItemFactory instead.");
            }

            return Activator.CreateInstance(itemType);
        }

        protected virtual void OnCollectionChanged(EventArgs e)
        {
            EventHandler handler = CollectionChanged;
            if (handler != null)
                handler(this, e);
        }

        protected virtual void OnSelectedItemChanged(EventArgs e)
        {
            EventHandler handler = SelectedItemChanged;
            if (handler != null)
                handler(this, e);
        }

        protected virtual void OnItemAdded(CollectionItemEventArgs e)
        {
            EventHandler<CollectionItemEventArgs> handler = ItemAdded;
            if (handler != null)
                handler(this, e);
        }

        protected virtual void OnItemRemoved(CollectionItemEventArgs e)
        {
            EventHandler<CollectionItemEventArgs> handler = ItemRemoved;
            if (handler != null)
                handler(this, e);
        }

        protected virtual void OnItemCreating(CollectionItemCreatingEventArgs e)
        {
            EventHandler<CollectionItemCreatingEventArgs> handler = ItemCreating;
            if (handler != null)
                handler(this, e);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                DetachCollectionNotifications();
                DetachSelectedItemNotification();
            }

            base.Dispose(disposing);
        }

        private static ToolStripButton CreateButton(string text, string toolTip)
        {
            return new ToolStripButton
            {
                Text = text,
                ToolTipText = toolTip,
                DisplayStyle = ToolStripItemDisplayStyle.Text,
                AutoSize = true
            };
        }

        private void SetItems(IList value)
        {
            if (ReferenceEquals(_items, value))
            {
                RefreshItems(true);
                return;
            }

            DetachCollectionNotifications();
            DetachSelectedItemNotification();

            _items = value;
            _inferredItemType = InferItemType(_declaredCollectionType, _items);

            AttachCollectionNotifications();
            RefreshItems(false);
        }

        private void ResolveCollectionFromSelectedObject()
        {
            if (_selectedObject == null)
            {
                _declaredCollectionType = null;
                SetItems(null);
                return;
            }

            IList directList = _selectedObject as IList;
            if (directList != null && string.IsNullOrWhiteSpace(_collectionPropertyName))
            {
                _declaredCollectionType = _selectedObject.GetType();
                SetItems(directList);
                return;
            }

            PropertyDescriptor property = null;
            PropertyDescriptorCollection properties = TypeDescriptor.GetProperties(_selectedObject);

            if (!string.IsNullOrWhiteSpace(_collectionPropertyName))
            {
                property = properties.Find(_collectionPropertyName, false);
                if (property == null)
                {
                    SetItems(null);
                    throw new ArgumentException(
                        "Property '" + _collectionPropertyName + "' was not found on " +
                        _selectedObject.GetType().FullName + ".",
                        nameof(CollectionPropertyName));
                }
            }
            else
            {
                List<PropertyDescriptor> candidates = new List<PropertyDescriptor>();
                foreach (PropertyDescriptor candidate in properties)
                {
                    if (IsListPropertyType(candidate.PropertyType))
                        candidates.Add(candidate);
                }

                if (candidates.Count == 1)
                {
                    property = candidates[0];
                    _collectionPropertyName = property.Name;
                }
                else
                {
                    SetItems(null);
                    return;
                }
            }

            _declaredCollectionType = property.PropertyType;
            object value = property.GetValue(_selectedObject);

            if (value == null)
            {
                if (property.IsReadOnly)
                {
                    SetItems(null);
                    throw new InvalidOperationException(
                        "Collection property '" + property.Name + "' is null and read-only.");
                }

                value = CreateCollectionInstance(property.PropertyType);
                property.SetValue(_selectedObject, value);
            }

            IList list = value as IList;
            if (list == null)
            {
                SetItems(null);
                throw new InvalidOperationException(
                    "Property '" + property.Name + "' does not implement System.Collections.IList.");
            }

            SetItems(list);
        }

        private static object CreateCollectionInstance(Type collectionType)
        {
            if (collectionType.IsInterface || collectionType.IsAbstract)
            {
                Type itemType = InferItemType(collectionType, null);
                if (itemType != null)
                {
                    Type listType = typeof(List<>).MakeGenericType(itemType);
                    if (collectionType.IsAssignableFrom(listType))
                        return Activator.CreateInstance(listType);
                }

                throw new InvalidOperationException(
                    "Cannot automatically create collection type " + collectionType.FullName + ".");
            }

            ConstructorInfo constructor = collectionType.GetConstructor(Type.EmptyTypes);
            if (constructor == null)
            {
                throw new InvalidOperationException(
                    "Collection type " + collectionType.FullName +
                    " does not have a public parameterless constructor.");
            }

            return Activator.CreateInstance(collectionType);
        }

        private void RefreshItems(bool preserveSelection)
        {
            if (_refreshing)
                return;

            _refreshing = true;
            try
            {
                object previousItem = preserveSelection ? _itemsList.SelectedItem : null;
                int previousIndex = preserveSelection ? _itemsList.SelectedIndex : -1;

                _itemsList.BeginUpdate();
                try
                {
                    _itemsList.Items.Clear();
                    if (_items != null)
                    {
                        foreach (object item in _items)
                            _itemsList.Items.Add(item);
                    }
                }
                finally
                {
                    _itemsList.EndUpdate();
                }

                int selectionIndex = -1;
                if (previousItem != null)
                    selectionIndex = FindItemIndex(previousItem);
                if (selectionIndex < 0 && previousIndex >= 0 && previousIndex < _itemsList.Items.Count)
                    selectionIndex = previousIndex;
                if (selectionIndex < 0 && _itemsList.Items.Count > 0)
                    selectionIndex = 0;

                _itemsList.SelectedIndex = selectionIndex;
                UpdateSelectedItem();
                UpdateViewState();
            }
            finally
            {
                _refreshing = false;
            }
        }

        private int FindItemIndex(object target)
        {
            for (int i = 0; i < _itemsList.Items.Count; i++)
            {
                object candidate = _itemsList.Items[i];
                if (ReferenceEquals(candidate, target) || Equals(candidate, target))
                    return i;
            }

            return -1;
        }

        private void ItemsList_SelectedIndexChanged(object sender, EventArgs e)
        {
            if (_refreshing)
                return;

            UpdateSelectedItem();
            UpdateCommandState();
            OnSelectedItemChanged(EventArgs.Empty);
        }

        private void UpdateSelectedItem()
        {
            DetachSelectedItemNotification();

            object selected = _itemsList.SelectedItem;
            _propertyGrid.SelectedObject = selected;
            _propertyGrid.Enabled = _allowPropertyEditing && selected != null;

            _selectedItemNotifier = selected as INotifyPropertyChanged;
            if (_selectedItemNotifier != null)
                _selectedItemNotifier.PropertyChanged += SelectedItemNotifier_PropertyChanged;
        }

        private void DetachSelectedItemNotification()
        {
            if (_selectedItemNotifier != null)
            {
                _selectedItemNotifier.PropertyChanged -= SelectedItemNotifier_PropertyChanged;
                _selectedItemNotifier = null;
            }
        }

        private void SelectedItemNotifier_PropertyChanged(object sender, PropertyChangedEventArgs e)
        {
            RunOnUiThread(delegate
            {
                _itemsList.Refresh();
                _propertyGrid.Refresh();
            });
        }

        private void ItemsList_Format(object sender, ListControlConvertEventArgs e)
        {
            e.Value = GetItemDisplayText(e.ListItem);
        }

        private string GetItemDisplayText(object item)
        {
            if (item == null)
                return "(null)";

            if (!string.IsNullOrWhiteSpace(_displayMember))
            {
                PropertyDescriptor property = TypeDescriptor.GetProperties(item).Find(_displayMember, true);
                if (property != null)
                {
                    object value = property.GetValue(item);
                    return Convert.ToString(value, CultureInfo.CurrentCulture) ?? string.Empty;
                }
            }

            return Convert.ToString(item, CultureInfo.CurrentCulture) ?? item.GetType().Name;
        }

        private void PropertyGrid_PropertyValueChanged(object s, PropertyValueChangedEventArgs e)
        {
            // PropertyGrid edits a boxed copy when the item is a struct. Write that
            // box back into the real collection so value-type edits are not lost.
            int index = _itemsList.SelectedIndex;
            object selected = _propertyGrid.SelectedObject;
            if (_items != null && index >= 0 && selected != null &&
                selected.GetType().IsValueType && !_items.IsReadOnly)
            {
                BeginInternalCollectionChange();
                try
                {
                    _items[index] = selected;
                }
                finally
                {
                    EndInternalCollectionChange();
                }
            }

            _itemsList.Refresh();

            PropertyValueChangedEventHandler handler = ItemPropertyValueChanged;
            if (handler != null)
                handler(this, e);

            OnCollectionChanged(EventArgs.Empty);
        }

        private void ItemsList_KeyDown(object sender, KeyEventArgs e)
        {
            if (e.KeyCode == Keys.Insert)
            {
                AddItem();
                e.Handled = true;
                e.SuppressKeyPress = true;
            }
            else if (e.KeyCode == Keys.Delete)
            {
                RemoveSelectedItem();
                e.Handled = true;
                e.SuppressKeyPress = true;
            }
            else if (e.Control && e.KeyCode == Keys.Up)
            {
                MoveSelectedItem(-1);
                e.Handled = true;
                e.SuppressKeyPress = true;
            }
            else if (e.Control && e.KeyCode == Keys.Down)
            {
                MoveSelectedItem(1);
                e.Handled = true;
                e.SuppressKeyPress = true;
            }
            else if (e.KeyCode == Keys.F5)
            {
                RefreshItems(true);
                e.Handled = true;
                e.SuppressKeyPress = true;
            }
        }

        private void MoveSelectedItem(int offset)
        {
            int oldIndex = _itemsList.SelectedIndex;
            int newIndex = oldIndex + offset;

            if (!CanModifyCollection() || !_allowReorder ||
                oldIndex < 0 || newIndex < 0 || newIndex >= _items.Count)
                return;

            object item = _items[oldIndex];
            bool removed = false;

            try
            {
                BeginInternalCollectionChange();
                try
                {
                    _items.RemoveAt(oldIndex);
                    removed = true;
                    _items.Insert(newIndex, item);
                }
                catch
                {
                    if (removed)
                    {
                        try
                        {
                            int rollbackIndex = Math.Min(oldIndex, _items.Count);
                            _items.Insert(rollbackIndex, item);
                        }
                        catch
                        {
                            // Preserve the original exception. A failed rollback is reflected on refresh.
                        }
                    }

                    throw;
                }
                finally
                {
                    EndInternalCollectionChange();
                }

                RefreshItems(false);
                _itemsList.SelectedIndex = newIndex;
                OnCollectionChanged(EventArgs.Empty);
            }
            catch (Exception ex)
            {
                RefreshItems(true);
                HandleOperationFailure("reorder the selected item", ex);
            }
        }

        private bool CanModifyCollection()
        {
            return Enabled && _items != null && !_items.IsReadOnly && !_items.IsFixedSize;
        }

        private bool CanCreateItemAutomatically()
        {
            if (_itemFactory != null || ItemCreating != null)
                return true;

            Type itemType = ItemType;
            if (itemType == null)
                return false;
            if (Nullable.GetUnderlyingType(itemType) != null)
                return true;
            if (itemType == typeof(string) || itemType.IsValueType)
                return true;
            if (itemType.IsInterface || itemType.IsAbstract)
                return false;

            return itemType.GetConstructor(Type.EmptyTypes) != null;
        }

        private void UpdateCommandState()
        {
            bool canModify = CanModifyCollection();
            int index = _itemsList.SelectedIndex;
            int count = _items == null ? 0 : _items.Count;

            _addButton.Enabled = canModify && _allowAdd && CanCreateItemAutomatically();
            _removeButton.Enabled = canModify && _allowRemove && index >= 0;
            _moveUpButton.Enabled = canModify && _allowReorder && index > 0;
            _moveDownButton.Enabled = canModify && _allowReorder && index >= 0 && index < count - 1;
            _refreshButton.Enabled = Enabled && _items != null;
            _itemsList.Enabled = Enabled && _items != null;
            _propertyGrid.Enabled = Enabled && _allowPropertyEditing && _itemsList.SelectedItem != null;
        }

        private void UpdateViewState()
        {
            int count = _items == null ? 0 : _items.Count;
            _countLabel.Text = count == 1 ? "1 item" : count.ToString(CultureInfo.CurrentCulture) + " items";

            bool hasCollection = _items != null;
            _emptyLabel.Visible = !hasCollection;
            _itemsList.Visible = hasCollection;
            _emptyLabel.BringToFront();
            if (hasCollection)
                _itemsList.BringToFront();

            UpdateCommandState();
        }

        private void AttachCollectionNotifications()
        {
            if (_items == null)
                return;

            _bindingList = _items as IBindingList;
            if (_bindingList != null)
            {
                _bindingList.ListChanged += BindingList_ListChanged;
                return;
            }

            _notifyCollection = _items as INotifyCollectionChanged;
            if (_notifyCollection != null)
                _notifyCollection.CollectionChanged += NotifyCollection_CollectionChanged;
        }

        private void DetachCollectionNotifications()
        {
            if (_bindingList != null)
            {
                _bindingList.ListChanged -= BindingList_ListChanged;
                _bindingList = null;
            }

            if (_notifyCollection != null)
            {
                _notifyCollection.CollectionChanged -= NotifyCollection_CollectionChanged;
                _notifyCollection = null;
            }
        }

        private void BindingList_ListChanged(object sender, ListChangedEventArgs e)
        {
            if (_internalChangeDepth > 0)
                return;

            RunOnUiThread(delegate { RefreshItems(true); });
        }

        private void NotifyCollection_CollectionChanged(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (_internalChangeDepth > 0)
                return;

            RunOnUiThread(delegate { RefreshItems(true); });
        }

        private void BeginInternalCollectionChange()
        {
            _internalChangeDepth++;
        }

        private void EndInternalCollectionChange()
        {
            if (_internalChangeDepth > 0)
                _internalChangeDepth--;
        }

        private void RunOnUiThread(MethodInvoker action)
        {
            if (IsDisposed || Disposing)
                return;

            if (IsHandleCreated && InvokeRequired)
            {
                BeginInvoke(action);
                return;
            }

            action();
        }

        private void HandleOperationFailure(string operation, Exception exception)
        {
            CollectionEditorOperationFailedEventArgs args =
                new CollectionEditorOperationFailedEventArgs(operation, exception);

            EventHandler<CollectionEditorOperationFailedEventArgs> handler = OperationFailed;
            if (handler != null)
                handler(this, args);

            if (!args.Handled && _showOperationErrors && !(exception is OperationCanceledException))
            {
                MessageBox.Show(
                    FindForm(),
                    "Could not " + operation + ".\r\n\r\n" + exception.Message,
                    "Collection editor",
                    MessageBoxButtons.OK,
                    MessageBoxIcon.Error);
            }
        }

        private static bool IsNonNullableValueType(Type type)
        {
            return type != null && type.IsValueType && Nullable.GetUnderlyingType(type) == null;
        }


        private static bool IsListPropertyType(Type type)
        {
            if (type == null)
                return false;
            if (typeof(IList).IsAssignableFrom(type))
                return true;

            if (type.IsGenericType && type.GetGenericTypeDefinition() == typeof(IList<>))
                return true;

            Type[] interfaces = type.GetInterfaces();
            for (int i = 0; i < interfaces.Length; i++)
            {
                Type candidate = interfaces[i];
                if (candidate.IsGenericType &&
                    candidate.GetGenericTypeDefinition() == typeof(IList<>))
                    return true;
            }

            return false;
        }

        private static Type InferItemType(Type declaredCollectionType, IList items)
        {
            Type itemType = FindGenericItemType(declaredCollectionType);
            if (itemType != null)
                return itemType;

            if (items != null)
            {
                itemType = FindGenericItemType(items.GetType());
                if (itemType != null)
                    return itemType;

                foreach (object item in items)
                {
                    if (item != null)
                        return item.GetType();
                }
            }

            return null;
        }

        private static Type FindGenericItemType(Type collectionType)
        {
            if (collectionType == null)
                return null;

            if (collectionType.IsArray)
                return collectionType.GetElementType();

            Type direct = GetKnownGenericItemType(collectionType);
            if (direct != null)
                return direct;

            Type[] interfaces = collectionType.GetInterfaces();
            for (int i = 0; i < interfaces.Length; i++)
            {
                Type candidate = GetKnownGenericItemType(interfaces[i]);
                if (candidate != null)
                    return candidate;
            }

            return null;
        }

        private static Type GetKnownGenericItemType(Type type)
        {
            if (!type.IsGenericType)
                return null;

            Type definition = type.GetGenericTypeDefinition();
            if (definition == typeof(IList<>) ||
                definition == typeof(ICollection<>) ||
                definition == typeof(IEnumerable<>) ||
                definition == typeof(BindingList<>))
            {
                return type.GetGenericArguments()[0];
            }

            return null;
        }
    }

    public sealed class CollectionItemEventArgs : EventArgs
    {
        public CollectionItemEventArgs(object item, int index)
        {
            Item = item;
            Index = index;
        }

        public object Item { get; private set; }
        public int Index { get; private set; }
    }

    public sealed class CollectionItemCreatingEventArgs : EventArgs
    {
        public CollectionItemCreatingEventArgs(Type itemType)
        {
            ItemType = itemType;
        }

        public Type ItemType { get; private set; }
        public object Item { get; set; }
        public bool Cancel { get; set; }
    }

    public sealed class CollectionEditorOperationFailedEventArgs : EventArgs
    {
        public CollectionEditorOperationFailedEventArgs(string operation, Exception exception)
        {
            Operation = operation;
            Exception = exception;
        }

        public string Operation { get; private set; }
        public Exception Exception { get; private set; }
        public bool Handled { get; set; }
    }
}