using System.ComponentModel;
using System.Diagnostics;
using System.Drawing.Design;
using Plankton.PluginApiImplementation;
using PluginApi;

namespace Plankton.Core.PreferenceEditor;

// Generated by Chatty G.

internal sealed class PreferencesForm : Form
{
    private readonly PreferencesService preferencesService;

    private readonly ListBox sectionList;
    private readonly PropertyGrid propertyGrid;
    private readonly Button applyButton;
    private readonly Button okButton;
    private readonly Button cancelButton;

    private readonly Dictionary<string, object> editableCopies = new();

    public PreferencesForm(PreferencesService preferencesService)
    {
        this.preferencesService = preferencesService;

        Text = "Preferences";
        StartPosition = FormStartPosition.CenterParent;
        MinimumSize = new Size(700, 500);
        Size = new Size(850, 600);

        sectionList = new ListBox
        {
            Dock = DockStyle.Fill,
            IntegralHeight = false,
            DisplayMember = nameof(PreferenceSection.Name)
        };

        propertyGrid = new PropertyGrid
        {
            Dock = DockStyle.Fill,
            ToolbarVisible = false,
            HelpVisible = true,
            PropertySort = PropertySort.Categorized
        };

        applyButton = new Button
        {
            Text = "Apply",
            AutoSize = true
        };

        okButton = new Button
        {
            Text = "OK",
            AutoSize = true
        };

        cancelButton = new Button
        {
            Text = "Cancel",
            AutoSize = true
        };

        var split = new SplitContainer
        {
            Dock = DockStyle.Fill,
            FixedPanel = FixedPanel.Panel1,
            SplitterDistance = 180
        };

        split.Panel1.Controls.Add(sectionList);
        split.Panel2.Controls.Add(propertyGrid);

        var buttons = new FlowLayoutPanel
        {
            Dock = DockStyle.Bottom,
            FlowDirection = FlowDirection.RightToLeft,
            AutoSize = true,
            Padding = new Padding(8)
        };

        buttons.Controls.Add(cancelButton);
        buttons.Controls.Add(okButton);
        buttons.Controls.Add(applyButton);

        Controls.Add(split);
        Controls.Add(buttons);

        AcceptButton = okButton;
        CancelButton = cancelButton;

        sectionList.SelectedIndexChanged += SectionList_SelectedIndexChanged;

        applyButton.Click += (_, _) => ApplyChanges();

        okButton.Click += (_, _) =>
        {
            ApplyChanges();
            DialogResult = DialogResult.OK;
            Close();
        };

        cancelButton.Click += (_, _) =>
        {
            DialogResult = DialogResult.Cancel;
            Close();
        };

        LoadPreferences();
    }

    private void LoadPreferences()
    {
        foreach (PreferenceSection section in preferencesService.Sections)
        {
            editableCopies.Add(
                section.Id,
                preferencesService.Clone(section.Value));

            sectionList.Items.Add(section);
        }

        if (sectionList.Items.Count > 0)
            sectionList.SelectedIndex = 0;
    }

    private void SectionList_SelectedIndexChanged(
        object? sender,
        EventArgs e)
    {
        if (sectionList.SelectedItem is not PreferenceSection section)
        {
            propertyGrid.SelectedObject = null;
            return;
        }

        object editableObject =
            editableCopies[section.Id];

        TypeDescriptor.Refresh(editableObject.GetType());
        propertyGrid.SelectedObject = editableObject;
    }

    private void ApplyChanges()
    {

        foreach (PreferenceSection section in preferencesService.Sections)
        {
            preferencesService.CopyInto(
                editableCopies[section.Id],
                section.Value);
        }

        preferencesService.Save();
    }
}